### ISSUE TITLE
undefined symbol "IsNullVector"

### ISSUE THREAD

**Issue by phorcep** [Rainyan/sourcemod-nt-anti-ghosthop#2]
Not sure what SM versions this is targeting, but it doesn't compile here:

```
SourcePawn Compiler 1.8.0.5928
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2015 AlliedModders LLC

nt_anti_ghosthop.sp(126) : error 017: undefined symbol "IsNullVector"

1 Error.
```

**Comment by Rainyan** [comment]
Thanks for reporting. There's no supported SM range specified yet as the plugin's still a bit in development–I've been working with latest stable SM for now, that being said supporting 1.8 does seem easy enough in this case.

I've changed the code with the missing symbol so should it should work on 1.8 now.

**Comment by Rainyan** [comment]
I'm closing this issue since 1.8 compiling should now be properly supported.

If you still have trouble compiling, feel free to re-open the issue!
